services:
  # backend:
  #   build:
  #     context: ./jewelry
  #     dockerfile: Dockerfile
  #   container_name: jewelry-backend
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network
  fe-management:
    build:
      context: ./shiny-management
      dockerfile: Dockerfile
    container_name: jewelry-management
    # depends_on:
    #   - backend
    ports:
      - "5174:80"
    networks:
      - app-network
  fe-user:
    build:
      context: ./shiny-website-ui
      dockerfile: Dockerfile
    container_name: jewelry-user
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
