import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { MANAGER, STAFF } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [MANAGER, STAFF],
        subMenu: [
            {
                key: 'appsSales.dashboard',
                path: `${APP_PREFIX_PATH}/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.appsSales.dashboard',
                icon: 'sales',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsSales.productList',
                path: `${APP_PREFIX_PATH}/products`,
                title: 'Products',
                translateKey: 'nav.appsSales.products',
                icon: 'sharedComponentDoc',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsCrm.customers',
                path: `${APP_PREFIX_PATH}/customers`,
                title: 'Customers',
                translateKey: 'nav.appsCrm.customers',
                icon: 'crm',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER, STAFF],
                subMenu: [],
            },
            {
                key: 'appsCrm.staffManagement',
                path: `${APP_PREFIX_PATH}/staffs`,
                title: 'Staffs',
                translateKey: 'nav.appsCrm.staffs',
                icon: 'crm',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsSales.orderList',
                path: `${APP_PREFIX_PATH}/orders`,
                title: 'Orders',
                translateKey: 'nav.appsSales.orders',
                icon: 'crypto',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ STAFF],
                subMenu: [],
            },
            {
                key: 'appsSales.catalogManagement',
                path: `${APP_PREFIX_PATH}/catalogs`,
                title: 'Catalog',
                translateKey: 'nav.appsSales.catalogManagement',
                icon: 'knowledgeBase',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsSales.reviews',
                path: `${APP_PREFIX_PATH}/reviews`,
                title: 'Reviews',
                translateKey: 'nav.sales.reviews',
                icon: 'documentation',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ STAFF],
                subMenu: [],
            },
            {
                key: 'appsSales.vouchers',
                path: `${APP_PREFIX_PATH}/vouchers`,
                title: 'Vouchers',
                translateKey: 'nav.sales.vouchers',
                icon: 'common',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsSales.webContent',
                path: `${APP_PREFIX_PATH}/web-content`,
                title: 'Web Content',
                translateKey: 'nav.sales.webContent',
                icon: 'common',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [MANAGER],
                subMenu: [],
            },
            {
                key: 'appsAccount.settings',
                path: `${APP_PREFIX_PATH}/account/settings/profile`,
                title: 'Account',
                translateKey: 'nav.appsAccount.account',
                icon: 'account',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [MANAGER, STAFF],
                subMenu: [],
            },
        ],
    },
]

export default appsNavigationConfig
