server {
    listen 80;
    server_tokens off;


    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;

        etag off;
        add_header Last-Modified "";
        add_header Date "";
        add_header X-Content-Type-Options "nosniff";
        add_header Content-Security-Policy "
          default-src 'self';
          script-src 'self';
          style-src 'self' https://fonts.googleapis.com;
          img-src 'self' data: https://cdn.pnj.io http://localhost:8080;
          font-src 'self' https://fonts.gstatic.com;
          connect-src 'self' http://localhost:8080;
          form-action 'self' http://localhost:8080;
          frame-ancestors 'none';
        " always;
        add_header X-Frame-Options "DENY" always;
    }
}
