name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        
    - name: Deploy with Docker Compose
      run: |
        # Copy files to the server
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }}:/home/app/jewelry_shop/
        
        # Deploy only backend and frontend services
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_IP }} << 'EOF'
          cd /home/app/jewelry_shop
          
          # Stop and rebuild only backend and frontend services
          docker compose stop backend fe-management fe-user
          docker compose rm -f backend fe-management fe-user
          docker compose build --no-cache backend fe-management fe-user
          docker compose up -d backend fe-management fe-user

           docker image prune -f
          
          # Show running containers
          docker compose ps
        EOF
